#index:
#    path: /
#    controller: App\Controller\HomeController::index
#
#secret:
#    path: /secret/
#    controller: App\Controller\SecretController::index
#
#secret-hash:
#    path: /secret/{hash}
#    controller: App\Controller\SecretController::index
#